### PR TITLE
Update example to use correct async function syntax

### PR DESCRIPTION
**Pull request by madd512**
Async arrow functions are not valid

### CODE REVIEW

**Comment by shinnn** [comment]
> Async arrow functions are not valid

That's news to me. Is there any sources?

**Comment by devTristan** [comment]
https://jakearchibald.com/2014/es7-async-functions/

https://github.com/tc39/ecmascript-asyncawait/issues/7

**Comment by knpwrs** [comment]
Now I'm sad. :sob:

**Comment by Ajedi32** [comment]
FYI, async arrow functions absolutely do exist. They're [mentioned in the spec](http://tc39.github.io/ecmascript-asyncawait/#prod-AsyncArrowFunction) and [work fine in Babel](https://babeljs.io/repl/#?evaluate=true&presets=es2015%2Creact%2Cstage-2&experimental=true&loose=false&spec=false&code=function%20delayedPromise(time%2C%20value)%20%7B%0D%0A%20%20return%20new%20Promise(function(resolve%2C%20reject)%20%7B%0D%0A%20%20%20%20setTimeout(()%20%3D%3E%20resolve(value)%2C%20time)%0D%0A%20%20%7D)%0D%0A%7D%0D%0A%0D%0Aasync%20function%20all()%20%7B%0D%0A%20%20let%20promises%20%3D%20range(0%2C%2010).map((i)%20%3D%3E%20delayedPromise(Math.random()%20*%201000%2C%20i))%0D%0A%20%20await%20Promise.all(promises.map(async%20(promise)%20%3D%3E%20console.log(%22Resolved%20all%3A%20%22%20%2B%20await%20promise)))%0D%0A%0D%0A%20%20console.log(%22Done%20with%20all!%22)%0D%0A%7D%0D%0A%0D%0Afunction%20range(start%2C%20count)%20%7B%0D%0A%20%20return%20Array.apply(0%2C%20Array(count))%0D%0A%20%20%20%20.map(function%20(element%2C%20index)%20%7B%20%0D%0A%20%20%20%20%20%20return%20index%20%2B%20start%3B%20%20%0D%0A%20%20%20%20%7D)%3B%0D%0A%7D%0D%0A%0D%0Aall()).

The blog post you cited is incorrect about async arrow functions not existing, and the tc39 issue you linked had the OP trying to use `await` in a _synchronous_ arrow function, not an asynchronous one.

**Pull request closed without merging**
